actions = \
	changelog \
	check \
	check-api \
	check-dependencies \
	check-docs \
	check-quality \
	check-types \
	clean \
	coverage \
	docs \
	{%- if repository_provider == "github.com" %}
	docs-deploy \
	{%- endif %}
	format \
	help \
	release \
	run \
	setup \
	test \
	vscode

.PHONY: $(actions)
$(actions):
	@:
